// <auto-generated />
using System;
using EF_Core_MVC_Code.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF_Core_MVC_Code.Migrations
{
    [DbContext(typeof(KutuphaneSabahContext))]
    partial class KutuphaneSabahContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Turkish_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EF_Core_MVC_Code.Models.Kitaplar", b =>
                {
                    b.Property<string>("Isbn")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("ISBN");

                    b.Property<string>("Ad")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("SayfaSayisi")
                        .HasColumnType("int");

                    b.Property<int?>("Stok")
                        .HasColumnType("int");

                    b.Property<int?>("TurlerId")
                        .HasColumnType("int")
                        .HasColumnName("TurID");

                    b.Property<int?>("YayinEvleriId")
                        .HasColumnType("int")
                        .HasColumnName("YayinEviID");

                    b.Property<int?>("YazarlarId")
                        .HasColumnType("int")
                        .HasColumnName("YazarID");

                    b.HasKey("Isbn")
                        .HasName("PK__Kitaplar__447D36EBC8C9DD62");

                    b.HasIndex("TurlerId");

                    b.HasIndex("YayinEvleriId");

                    b.HasIndex("YazarlarId");

                    b.ToTable("Kitaplar");
                });

            modelBuilder.Entity("EF_Core_MVC_Code.Models.Odunc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Iptal")
                        .HasColumnType("bit");

                    b.Property<string>("KitaplarIsbn")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("KitaplarISBN");

                    b.Property<DateTime?>("TeslimTarihi")
                        .HasColumnType("date");

                    b.Property<int?>("UyeId")
                        .HasColumnType("int")
                        .HasColumnName("UyeID");

                    b.Property<DateTime?>("VerilisTarihi")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("KitaplarIsbn");

                    b.HasIndex("UyeId");

                    b.ToTable("Odunc");
                });

            modelBuilder.Entity("EF_Core_MVC_Code.Models.Turler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TurAd")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TurAd" }, "UQ__Turler__A1D0193D816FCF10")
                        .IsUnique()
                        .HasFilter("[TurAd] IS NOT NULL");

                    b.ToTable("Turler");
                });

            modelBuilder.Entity("EF_Core_MVC_Code.Models.Uyeler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdSoyad")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<bool?>("CezaDurumu")
                        .HasColumnType("bit");

                    b.Property<string>("Cinsiyet")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("date");

                    b.Property<int?>("EgitimDurumu")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Meslek")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TcNo")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Tel")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime?>("UyelikTarihi")
                        .HasColumnType("date");

                    b.Property<int?>("UyelikTipi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Uyeler");
                });

            modelBuilder.Entity("EF_Core_MVC_Code.Models.Yayinevleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Adres")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Tel")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Ad" }, "UQ__Yayinevl__3214AD00DD60C7E3")
                        .IsUnique()
                        .HasFilter("[Ad] IS NOT NULL");

                    b.ToTable("Yayinevleri");
                });

            modelBuilder.Entity("EF_Core_MVC_Code.Models.Yazarlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdSoyad")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Cinsiyet")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Mail")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Tel")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<int?>("TurlerId")
                        .HasColumnType("int")
                        .HasColumnName("TurID");

                    b.HasKey("Id");

                    b.HasIndex("TurlerId");

                    b.ToTable("Yazarlar");
                });

            modelBuilder.Entity("EF_Core_MVC_Code.Models.Kitaplar", b =>
                {
                    b.HasOne("EF_Core_MVC_Code.Models.Turler", "Turler")
                        .WithMany("Kitaplars")
                        .HasForeignKey("TurlerId")
                        .HasConstraintName("FK__Kitaplar__Turler__4222D4EF")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EF_Core_MVC_Code.Models.Yayinevleri", "YayinEvleri")
                        .WithMany("Kitaplars")
                        .HasForeignKey("YayinEvleriId")
                        .HasConstraintName("FK__Kitaplar__YayinE__440B1D61")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EF_Core_MVC_Code.Models.Yazarlar", "Yazarlar")
                        .WithMany("Kitaplars")
                        .HasForeignKey("YazarlarId")
                        .HasConstraintName("FK__Kitaplar__Yazarl__4316F928");

                    b.Navigation("Turler");

                    b.Navigation("YayinEvleri");

                    b.Navigation("Yazarlar");
                });

            modelBuilder.Entity("EF_Core_MVC_Code.Models.Odunc", b =>
                {
                    b.HasOne("EF_Core_MVC_Code.Models.Kitaplar", "KitaplarIsbnNavigation")
                        .WithMany("Oduncs")
                        .HasForeignKey("KitaplarIsbn")
                        .HasConstraintName("FK__Odunc__KitaplarI__47DBAE45")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EF_Core_MVC_Code.Models.Uyeler", "Uye")
                        .WithMany("Oduncs")
                        .HasForeignKey("UyeId")
                        .HasConstraintName("FK__Odunc__UyeID__46E78A0C")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("KitaplarIsbnNavigation");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("EF_Core_MVC_Code.Models.Yazarlar", b =>
                {
                    b.HasOne("EF_Core_MVC_Code.Models.Turler", "Turler")
                        .WithMany("Yazarlars")
                        .HasForeignKey("TurlerId")
                        .HasConstraintName("FK__Yazarlar__Turler__3A81B327")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Turler");
                });

            modelBuilder.Entity("EF_Core_MVC_Code.Models.Kitaplar", b =>
                {
                    b.Navigation("Oduncs");
                });

            modelBuilder.Entity("EF_Core_MVC_Code.Models.Turler", b =>
                {
                    b.Navigation("Kitaplars");

                    b.Navigation("Yazarlars");
                });

            modelBuilder.Entity("EF_Core_MVC_Code.Models.Uyeler", b =>
                {
                    b.Navigation("Oduncs");
                });

            modelBuilder.Entity("EF_Core_MVC_Code.Models.Yayinevleri", b =>
                {
                    b.Navigation("Kitaplars");
                });

            modelBuilder.Entity("EF_Core_MVC_Code.Models.Yazarlar", b =>
                {
                    b.Navigation("Kitaplars");
                });
#pragma warning restore 612, 618
        }
    }
}
