// <auto-generated />
using System;
using GetLesson.Models.Concrete.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GetLesson.Migrations
{
    [DbContext(typeof(GetLessonContextDb))]
    [Migration("20220506061204_Mig_1")]
    partial class Mig_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GetLesson.Models.Entites.Departman", b =>
                {
                    b.Property<int>("DepartmanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmanMaganer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmanName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmanId");

                    b.ToTable("Departmans");
                });

            modelBuilder.Entity("GetLesson.Models.Entites.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Credit")
                        .HasColumnType("int");

                    b.Property<string>("LessonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LessonTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int");

                    b.HasKey("LessonId");

                    b.HasIndex("PeriodId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("GetLesson.Models.Entites.Period", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("int");

                    b.HasKey("PeriodId");

                    b.ToTable("Periods");
                });

            modelBuilder.Entity("GetLesson.Models.Entites.StudentInfo", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StudentBirtday")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StudentRegistration")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentSurName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("PeriodId");

                    b.ToTable("StudentInfos");
                });

            modelBuilder.Entity("GetLesson.Models.Entites.TakeLesson", b =>
                {
                    b.Property<int>("TakeLessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentInfoStudentId")
                        .HasColumnType("int");

                    b.HasKey("TakeLessonId");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentInfoStudentId");

                    b.ToTable("TakeLessons");
                });

            modelBuilder.Entity("GetLesson.Models.Entites.Lesson", b =>
                {
                    b.HasOne("GetLesson.Models.Entites.Period", "Period")
                        .WithMany("Lessons")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("GetLesson.Models.Entites.StudentInfo", b =>
                {
                    b.HasOne("GetLesson.Models.Entites.Departman", "Departman")
                        .WithMany("StudentInfos")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GetLesson.Models.Entites.Period", "Period")
                        .WithMany("StudentInfos")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departman");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("GetLesson.Models.Entites.TakeLesson", b =>
                {
                    b.HasOne("GetLesson.Models.Entites.Lesson", null)
                        .WithMany("TakeLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GetLesson.Models.Entites.StudentInfo", null)
                        .WithMany("TakeLessons")
                        .HasForeignKey("StudentInfoStudentId");
                });

            modelBuilder.Entity("GetLesson.Models.Entites.Departman", b =>
                {
                    b.Navigation("StudentInfos");
                });

            modelBuilder.Entity("GetLesson.Models.Entites.Lesson", b =>
                {
                    b.Navigation("TakeLessons");
                });

            modelBuilder.Entity("GetLesson.Models.Entites.Period", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("StudentInfos");
                });

            modelBuilder.Entity("GetLesson.Models.Entites.StudentInfo", b =>
                {
                    b.Navigation("TakeLessons");
                });
#pragma warning restore 612, 618
        }
    }
}
